--- The combat rules for each unit
return {
  LIGHT_INFANTRY = {
    ATTACKING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 2,
      LIGHT_VEHICLE  = 1,
      HEAVY_VEHICLE  = 0.5,
      HELICOPTER     = 1,
      COMMANDER      = 1,
    },
    DEFENDING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 1,
      HEAVY_VEHICLE  = 1,
      HELICOPTER     = 2,
      COMMANDER      = 0,
    },
  },
  HEAVY_INFANTRY = {
    ATTACKING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 2,
      HEAVY_VEHICLE  = 1,
      HELICOPTER     = 0.5,
      COMMANDER      = 1,
    },
    DEFENDING = {
      LIGHT_INFANTRY = 0.5,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 1,
      HEAVY_VEHICLE  = 1,
      HELICOPTER     = 1,
      COMMANDER      = 0,
    },
  },
  LIGHT_VEHICLE = {
    ATTACKING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 1,
      HEAVY_VEHICLE  = 0.5,
      HELICOPTER     = 2,
      COMMANDER      = 1,
    },
    DEFENDING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 0.5,
      LIGHT_VEHICLE  = 1,
      HEAVY_VEHICLE  = 0.5,
      HELICOPTER     = 2,
      COMMANDER      = 0,
    },
  },
  HEAVY_VEHICLE = {
    ATTACKING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 2,
      HEAVY_VEHICLE  = 1,
      HELICOPTER     = 0.5,
      COMMANDER      = 1,
    },
    DEFENDING = {
      LIGHT_INFANTRY = 2,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 2,
      HEAVY_VEHICLE  = 1,
      HELICOPTER     = 0.5,
      COMMANDER      = 0,
    },
  },
  HELICOPTER = {
    ATTACKING = {
      LIGHT_INFANTRY = 0.5,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 0.5,
      HEAVY_VEHICLE  = 2,
      HELICOPTER     = 1,
      COMMANDER      = 1,
    },
    DEFENDING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 2,
      LIGHT_VEHICLE  = 0.5,
      HEAVY_VEHICLE  = 2,
      HELICOPTER     = 1,
      COMMANDER      = 0,
    },
  },
  COMMANDER = {
    ATTACKING = {
      LIGHT_INFANTRY = 0,
      HEAVY_INFANTRY = 0,
      LIGHT_VEHICLE  = 0,
      HEAVY_VEHICLE  = 0,
      HELICOPTER     = 0,
      COMMANDER      = 0,
    },
    DEFENDING = {
      LIGHT_INFANTRY = 1,
      HEAVY_INFANTRY = 1,
      LIGHT_VEHICLE  = 1,
      HEAVY_VEHICLE  = 1,
      HELICOPTER     = 1,
      COMMANDER      = 0,
    },
  },
}
